name: Build Policy
on: [push, pull_request]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build container
        run: docker build -t unison-policy:ci .
