name: Publish container

on:
  push:
    branches: [ main, "release/**" ]
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write
  security-events: write

jobs:
  publish:
    uses: project-unisonOS/unison-platform/.github/workflows/reusable-build.yml@3346ebeb2e70704cc8ca903ebeacf2ba23be25f5
    with:
      image_name: unison-policy
      domain: policy
      service_port: "8083"
    secrets: inherit
